"""BhoomiLens API application factory."""

from __future__ import annotations

import time
import uuid
from typing import Any, Dict

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from .api import router
from .config import get_settings

DESCRIPTION = """
**BhoomiLens** — National Land Governance Intelligence Platform API.

The service exposes the land-record, acquisition, risk, validation, GIS,
compensation, anomaly and audit datasets that power the BhoomiLens interface.

* All list endpoints support `page`, `page_size`, `search`, `sort_by`, `sort_dir`,
  `state` and `district`.
* Every endpoint is guarded by a named permission; obtain a token from
  `POST /api/v1/auth/token?role=national_admin`.
* Predictive outputs are labelled: *Simulated prediction for prototype
  demonstration. Not a legal determination.*
* Anomaly outputs are labelled as **potential anomalies**, never confirmed fraud.
* This deployment serves synthetic data generated by a deterministic engine.
"""


def create_app() -> FastAPI:
    settings = get_settings()
    app = FastAPI(
        title="BhoomiLens API",
        description=DESCRIPTION,
        version="1.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json",
    )

    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_origin_list,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def correlation_and_timing(request: Request, call_next):
        correlation_id = request.headers.get("X-Correlation-Id") or f"COR-{uuid.uuid4().hex[:10]}"
        started = time.perf_counter()
        response = await call_next(request)
        response.headers["X-Correlation-Id"] = correlation_id
        response.headers["X-Response-Time-Ms"] = f"{(time.perf_counter() - started) * 1000:.1f}"
        return response

    @app.exception_handler(Exception)
    async def unhandled(request: Request, exc: Exception) -> JSONResponse:  # pragma: no cover
        return JSONResponse(
            status_code=500,
            content={
                "code": "internal_error",
                "message": "An unexpected error occurred.",
                "path": str(request.url.path),
            },
        )

    @app.get("/health", tags=["Platform"], summary="Liveness and readiness probe")
    def health() -> Dict[str, Any]:
        return {"status": "ok", "environment": settings.env, "version": "1.0.0"}

    @app.get("/", tags=["Platform"], summary="Service banner")
    def root() -> Dict[str, Any]:
        return {
            "service": "BhoomiLens API",
            "docs": "/docs",
            "openapi": "/openapi.json",
            "apiPrefix": settings.api_prefix,
            "notice": "Demonstration environment using synthetic data.",
        }

    app.include_router(router, prefix=settings.api_prefix)
    return app


app = create_app()
