import { appConfig } from '@/config/appConfig';
import { cn } from '@/lib/cn';

export function DemoBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        'chip border-signal-amber/50 bg-signal-amber/15 text-[#8a5f10]',
        className,
      )}
      title="All figures in this environment are generated by the BhoomiLens synthetic data engine."
    >
      ● {appConfig.demoBadge}
    </span>
  );
}

export function PredictionDisclaimer({ className }: { className?: string }) {
  return (
    <p className={cn('text-2xs italic text-muted', className)}>
      {appConfig.predictionDisclaimer}
    </p>
  );
}

export function AnomalyDisclaimer({ className }: { className?: string }) {
  return <p className={cn('text-2xs italic text-muted', className)}>{appConfig.anomalyDisclaimer}</p>;
}

export function ScoreDisclaimer({ className }: { className?: string }) {
  return <p className={cn('text-2xs italic text-muted', className)}>{appConfig.scoreDisclaimer}</p>;
}
